### ISSUE TITLE
CelesteNet Integration broken? 

### ISSUE THREAD

**Issue by RedFlames** [snomii/Hateline#1]
Hi!

Someone's complained that there's a "memory leak" issue with having CelesteNet and Hateline enabled and being in the same place as another player with it. And I can see why, I think.
Firstly I was a bit concerned to see that the hat info is sent every frame that the player gets updated? I don't quite see why, since perhaps sending it upon spawning the player should be fine, but I may be forgetting something.

More concerningly however, you seem to add a new component to the relevant Ghost for every hat update received. So at worst, a new HatComponent added per frame?...

May I suggest `ghost.Get<HatComponent>()` in the `Handle()` action and updating that with the new info? :D

**Comment by bunnerfly** [comment]
oh wtfrick
i knew my code was old and bad but i didn't realize it was THAT old and bad
i'll try this out

i don't check github much btw, message me on discord if u have problems -> `@eepbitfutures`

**Comment by RedFlames** [comment]
This is now officially fixed with 0.1.5 being released on GB
